### PR TITLE
Merge with latest upstream

### PR DESCRIPTION
**Pull request by chaitu236**
No conflicts, fast forward merge.

WI: [2006369](https://ni.visualstudio.com/DevCentral/_workitems/edit/2006369)

### Testing
bitbake operations working fine.

### CODE REVIEW

**Comment by chaitu236** [comment]
@amstewart / @shruthi-ravi I can't add reviewers - some setting needs to be changed?

**Comment by shruthi-ravi** [comment]
@chaitu236 how about now?

**Comment by chaitu236** [comment]
> @chaitu236 how about now?

Works now. Thanks!

**Review by amstewart — APPROVED** [review]

**Review by shruthi-ravi — APPROVED** [review]

**Comment by chaitu236** [comment]
@amstewart @shruthi-ravi can one of you merge this?

**Pull request merged**
